version = 3.9.10
runner.dialect = scala3
maxColumn = 100
align.preset = most
docstrings.style = Asterisk
newlines.source = keep
project.excludeFilters = [
  "out/.*"
  "\\.bsp/.*"
  "scripts/\\.bsp/.*"
  "scripts/\\.scala-build/.*"
]
